config/routes.rb
Rails.application.routes.draw do
  resources :welcomes
  get '/', to: 'greetings#index'
  resources :greetings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greeting.rb
class Greeting < ApplicationRecord
    has_rich_text :body
    validates :body, presence: true
    # broadcasts_to ->(greeting) {'greetings'}, target: :greetings
    # broadcasts
    after_create_commit {broadcast_prepend_to 'greetings'}
    after_update_commit {broadcast_replace_to 'greetings'}
    after_destroy_commit {broadcast_remove_to 'greetings'}
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[ show edit update destroy ]

  # GET /greetings or /greetings.json
  def index
    @greetings = Greeting.order("id DESC").all
    @greeting = Greeting.new
  end

  # GET /greetings/1 or /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings or /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        # format.turbo_stream
        format.html { redirect_to greetings_path, notice: "Greeting was successfully created." }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@greeting, partial: 'greetings/form', locals: {greeting: @greeting}) }
      end
    end
  end

  # PATCH/PUT /greetings/1 or /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to @greeting, notice: "Greeting was successfully updated." }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1 or /greetings/1.json
  def destroy
    @greeting.destroy
    respond_to do |format|
      format.html { redirect_to greetings_url, notice: "Greeting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greeting
      @greeting = Greeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def greeting_params
      params.require(:greeting).permit(:body, :content)
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: %i[ show edit update destroy ]

  # GET /welcomes or /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1 or /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes or /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: "Welcome was successfully created." }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1 or /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: "Welcome was successfully updated." }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1 or /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: "Welcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def welcome_params
      params.require(:welcome).permit(:post)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/greetings/_form.html.erb
<%= form_with(model: greeting, id: dom_id(greeting)) do |form| %>
  <% if greeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/_greeting.html.erb
<%= turbo_frame_tag dom_id(greeting) do %>
    <div class="card"> 
        <div class='col greeting'>
            <h6><%= time_ago_in_words(greeting.created_at)%> ago Anonymous said:</h6>
            <p><%= greeting.body %></p>
        </div>
    </div>
    <span style="margin: 5px 5px 5px 0px; display:inline-block;">
         <%= button_to "Delete", greeting, :class => 'btn btn-light' , method: :delete %>
    </span>
    <span style="margin: 5px 5px 5px 0px; display:inline-block;">
        <%= button_to "Edit", edit_greeting_path(greeting), :class => 'btn btn-light',  method: 'get' %>
    </span>
<% end %>

app/views/greetings/edit.html.erb
<h1>Editing Greeting</h1>

<%= turbo_frame_tag dom_id(@greeting) do %>

    <%= render 'form', greeting: @greeting %>

    <div style="margin: 5px">
        <%= link_to 'Cancel', @greeting %>
    </div>
<% end %>

app/views/greetings/index.html.erb
<%= turbo_stream_from 'greetings' %>

<p id="notice"><%= notice %></p>

<div class="home-video-wrapper">
  <%= video_tag "arnold.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "home_video" %>
  <h1 class="home" id="home-text" style="color: white;">This is Bitlicious<br><%= link_to 'Enter Here', welcomes_path %></h1>
</div>
  
  <hr>
  
  <div class="container comment-container">
  
  <h1 class="header">Welcome to Bitlicious</h1>
  <h3>Drop me a line!</h3>

<%= turbo_frame_tag "greeting_form" do %>
  <%= render 'form', greeting: @greeting %>
<% end %>

<br>

<%= turbo_frame_tag "greetings" do %>
  <%= render @greetings %>
<% end %>

</div>

</div>

app/views/greetings/new.html.erb
<h1>New Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Back', greetings_path %>

app/views/greetings/show.html.erb
<%= turbo_frame_tag dom_id(@greeting) do %>
    <%= render @greeting %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>HotwireLanding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= yield %>


      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/welcomes/_form.html.erb
<%= form_with(model: welcome) do |form| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
        <% welcome.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post %>
    <%= form.text_area :post %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @welcome.post %>
</p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>